services:
  dns_yes_bot:
    build:
      context: ./DNS_YES_BOT/
      dockerfile: Dockerfile
    volumes:
      - dns_data:/app/data
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    user: "${UID}:${GID}"
    networks:
      - dns_net
    restart: unless-stopped
  
  interface:
    build:
      context: ./Interface/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7030
      - DOMAIN_NAME=localhost
      - ASPNETCORE_ENVIRONMENT=Production
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    user: "${UID}:${GID}"
    volumes:
      - shared_keys:/app/keys
    ports:
      - "7030:7030"
    networks:
      - dns_net
    restart: unless-stopped

networks:
  dns_net:
    driver: bridge

volumes:
  dns_data: {}
  shared_keys: {}